name: Image Push Complete
on:
  workflow_run:
    workflows: [Build & Push]
    types:
      - completed

jobs:
  Notify:
    name: Image Push Complete
    runs-on: ubuntu-latest
    steps:
    - name: send custom message with args
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK }}
        args: The ${{ github.event_name }} successfully pushed the image.

    - name: Discord notification
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
      with:
        args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} successfully pushed the image.'
     